name: biker
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+1
  cupertino_icons: ^0.1.2
  font_awesome_flutter:
  rxdart:
  flutter_masked_text:
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.7.0
  shared_preferences: ^0.5.1+1
  json_annotation: ^2.0.0
  path_provider: ^0.5.0+1
  url_launcher: ^5.0.1
  sqflite: ^1.1.0
  intl: ^0.15.7
  fluttertoast: ^2.2.11
  json_serializable: ^2.0.2
  flutter_cupertino_date_picker: ^0.3.0
  carousel_pro: ^0.0.13
  page_view_indicator: ^0.3.0+1
  flutter_search_panel: ^1.0.0
  animated_text_kit: ^1.3.0
  strings: ^0.1.0
  quick_actions: ^0.3.0+1
  charts_flutter: ^0.5.0
  query_params: ^0.6.1
  image_picker: ^0.4.12+1
  flutter_sparkline: ^0.1.0
  flutter_staggered_grid_view: ^0.2.7
  mask_shifter: ^0.1.0
  build_runner: ^1.2.6
  dio: ^2.0.10

dev_dependencies:
  random_pk:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - locale/i18n_en.json
    - locale/i18n_hi.json

  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/quicksand_medium.ttf
          style: normal
        - asset: assets/fonts/quicksand_bold.otf
          weight: 700


    - family: Raleway
      fonts:
        - asset: assets/fonts/raleway_regular.ttf
          style: normal
        - asset: assets/fonts/raleway_medium.ttf